name: Update

on:
  push:
    branches: [ master ]

jobs:
  versioning:
    if: github.repository == 'Thi-Vua-Lay-Tot/libot-leaderboard'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update
        id: new-version
        run: python update_version.py
      - name: Auto update
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-user"
          git add versioning.yml
          git commit -m "Auto update to ${{ steps.new-version.outputs.new_version }}"
          git push origin HEAD:master
